### ISSUE TITLE
Structurer le dépôt pour les utilitaires

### ISSUE THREAD

**Issue by jena-s-lab** [nyl-auster/csa-temps-de-parole#3]
Il faudrait au choix, non-exclusifs:
- Lister les utilitaires développés, et donc déplacer l'importateur python dans son propre projet.
- Faire des utilitaires "approuvés" des sous-modules du projet.

**Comment by yann-yinn** [comment]
On peut pour l'instant créer un dossier "parsers" (ou un autre nom pour designer tous les scripts qui mangent les csv pour en sortir un json)  et mettre dedans les dossiers pour le script python et le tien. cc @Teraglehn

**Comment by jena-s-lab** [comment]
Pour ma part j'ai sorti du dépôt et amélioré l'utilitaire, il est maintenant à https://github.com/kane-thornwyrd/csa-xlsx-converter.js et installable par `$ npm install csa-xlsx-converter`, importable comme module et utilisable en CLI.

**Comment by yann-yinn** [comment]
@kane-thornwyrd ok on regarde dès que possible avec @Teraglehn , ça devrait être en place aujourd'hui ou demain

**Comment by yann-yinn** [comment]
@kane-thornwyrd je viens d'intégrer ton module npm qui a l'air de très bien marcher, super taf 👍  . Il y a désormais un "build.sh" à la racine du projet qui fait tourner la moulinette.

Il y a moyen de changer le nom du fichier de sortie des fichiers ? le contenu de "dist" est théoriquement directement ce qui sera servi en statique sur "https://equite-parole.github.io/api"

**Comment by yann-yinn** [comment]
@kane-thornwyrd : ps par ailleurs la structure du projet se stabilise donc les pull requests deviennent envisageables

**Comment by yann-yinn** [comment]
hey @kane-thornwyrd , je peux te mentionner sur la page https://equite-parole.github.io/qui-sommes-nous/ quand ton boulot sera en ligne ? Sous quel nom / pseudo tu souhaites ?

**Comment by jena-s-lab** [comment]
Jean-cédric Thérond

**Comment by yann-yinn** [comment]
@kane-thornwyrd https://equite-parole.github.io/qui-sommes-nous/
